### ISSUE TITLE
GrailsParameterMap datatype is not supported

### ISSUE THREAD

**Issue by nsgraff** [rpalcolea/grails-xss-sanitizer#6]
If you add this to line 27 in the XssSanitizerInterceptor.groovy then when Grails data binds a list of parameters it will sanitize any Strings in the bounded params list.

}else if(entry.value instanceof grails.web.servlet.mvc.GrailsParameterMap) {
                sanitizeParameters(entry.value)
            }

**Comment by rpalcolea** [comment]
Hi @nsgraff ,

Thanks for the report and sorry for the delay `1.2.0` is released now!

https://bintray.com/rpalcolea/plugins/grails-xss-sanitizer/1.2.0
